CREATE TYPE user_role AS ENUM (
	'ADMIN',
	'USER'
);

CREATE TYPE report_status AS ENUM (
	'COMPLETED',
	'REJECTED',
	'PENDING',
	'IN_PROGRESS'
);

CREATE TABLE IF NOT EXISTS users (
    "id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(100) NOT NULL UNIQUE,
    "password_hash" VARCHAR(255) NOT NULL,
    "role" USER_ROLE NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS sessions (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "token" VARCHAR(255) NOT NULL UNIQUE,
    "expires_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS reports (
    "id" UUID NOT NULL,
    "version" BIGINT NOT NULL DEFAULT 0,
    "reporter_id" UUID NOT NULL,
    "category_id" UUID NOT NULL,
    "room_id" UUID NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "status" REPORT_STATUS NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    "deleted_at" TIMESTAMP,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS buildings (
    "id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "code" VARCHAR(255) NOT NULL UNIQUE,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS categories (
    "id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS report_images (
    "id" UUID NOT NULL,
    "report_id" UUID NOT NULL,
    "image_url" VARCHAR(255) NOT NULL,
    "uploaded_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
    );

CREATE TABLE IF NOT EXISTS upvotes (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "report_id" UUID NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);

CREATE UNIQUE INDEX upvotes_index_0
    ON upvotes ("user_id", "report_id");

CREATE TABLE IF NOT EXISTS rooms (
    "id" UUID NOT NULL,
    "building_id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "floor" INTEGER NOT NULL,
    "code" VARCHAR(255) NOT NULL UNIQUE,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS report_logs (
    "id" UUID NOT NULL,
    "admin_id" UUID NOT NULL,
    "report_id" UUID NOT NULL,
    "old_status" REPORT_STATUS NOT NULL,
    "new_status" REPORT_STATUS NOT NULL,
    "notes" TEXT,
    "created_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS user_stats (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL UNIQUE,
    "report_count" INTEGER NOT NULL,
    "pending_report" INTEGER NOT NULL,
    "completed_report" INTEGER NOT NULL,
    "rejected_report" INTEGER NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS idempotency_keys (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "key" VARCHAR(36) NOT NULL UNIQUE,
    "user_id" UUID NOT NULL,
    "request_path" VARCHAR(255) NOT NULL,
    "response_status" SMALLINT NOT NULL,
    "response_body" TEXT NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "expires_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);


CREATE INDEX idempotency_keys_index_0
    ON idempotency_keys ("user_id", "key");

ALTER TABLE report_logs
    ADD FOREIGN KEY("admin_id") REFERENCES users("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE report_logs
    ADD FOREIGN KEY("report_id") REFERENCES reports("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE reports
    ADD FOREIGN KEY("category_id") REFERENCES categories("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE reports
    ADD FOREIGN KEY("room_id") REFERENCES rooms("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE reports
    ADD FOREIGN KEY("reporter_id") REFERENCES users("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE report_images
    ADD FOREIGN KEY("report_id") REFERENCES reports("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE rooms
    ADD FOREIGN KEY("building_id") REFERENCES buildings("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE upvotes
    ADD FOREIGN KEY("report_id") REFERENCES reports("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE upvotes
    ADD FOREIGN KEY("user_id") REFERENCES users("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE sessions
    ADD FOREIGN KEY("user_id") REFERENCES users("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE user_stats
    ADD FOREIGN KEY("user_id") REFERENCES users("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE idempotency_keys
    ADD FOREIGN KEY("user_id") REFERENCES users("id") ON UPDATE NO ACTION ON DELETE CASCADE;